/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao.telas;

import controlador.CFornecedor;
import javax.swing.JOptionPane;
import modelo.dominio.Fornecedor;
import relatorios.RPCliente;
import relatorios.RPFornecedor;
import relatorios.RPFuncionario;
import relatorios.RPProduto;

/**
 *
 * @author IFTM
 */
public class CadastroFornecedor extends javax.swing.JFrame {

    /**
     * Creates new form CadastroFornecedor
     */
    public CadastroFornecedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboBoxGrupo = new javax.swing.JComboBox<>();
        campoCnpj = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoTelefone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoCidade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        campoEndereco = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        botaoCancelar1 = new javax.swing.JButton();
        botaoLimpar = new javax.swing.JButton();
        botaoSalvar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        transacoes1 = new javax.swing.JMenu();
        menuCliente1 = new javax.swing.JMenu();
        cadastrarCliente1 = new javax.swing.JMenuItem();
        visualizarCliente1 = new javax.swing.JMenuItem();
        alterarCliente1 = new javax.swing.JMenuItem();
        deletarCliente1 = new javax.swing.JMenuItem();
        menuFornecedor1 = new javax.swing.JMenu();
        cadastrarFornecedor1 = new javax.swing.JMenuItem();
        visualizarFornecedor1 = new javax.swing.JMenuItem();
        alterarFornecedor1 = new javax.swing.JMenuItem();
        deletarFornecedor1 = new javax.swing.JMenuItem();
        menuFuncionario1 = new javax.swing.JMenu();
        cadastrarFuncionario1 = new javax.swing.JMenuItem();
        visualizarFuncionarios1 = new javax.swing.JMenuItem();
        alterarFuncionario1 = new javax.swing.JMenuItem();
        deletarFuncionario1 = new javax.swing.JMenuItem();
        menuProduto1 = new javax.swing.JMenu();
        cadastrarProduto1 = new javax.swing.JMenuItem();
        vizualizarrProduto1 = new javax.swing.JMenuItem();
        alterarrProduto1 = new javax.swing.JMenuItem();
        deletarrProduto1 = new javax.swing.JMenuItem();
        relatorio = new javax.swing.JMenu();
        relatorioCliente = new javax.swing.JMenuItem();
        relatorioFornecedor = new javax.swing.JMenuItem();
        relatorioFuncionario = new javax.swing.JMenuItem();
        relatorioProduto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Fornecedor");

        comboBoxGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "   ", "Bebidas", "Mercearia seca doce", "Mercearia seca salgada", "Perecivel", "Perfumaria Hipel", " " }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Grupo de comprador:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("CNPJ:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Telefone:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Cidade:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Endereço:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Nome do Fornecedor:");

        botaoCancelar1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoCancelar1.setText("Cancelar");
        botaoCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelar1ActionPerformed(evt);
            }
        });

        botaoLimpar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoLimpar.setText("Limpar");
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });

        botaoSalvar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo.png"))); // NOI18N

        transacoes1.setText("Transações");

        menuCliente1.setText("Cliente");
        menuCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCliente1ActionPerformed(evt);
            }
        });

        cadastrarCliente1.setText("Cadastrar");
        cadastrarCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarCliente1ActionPerformed(evt);
            }
        });
        menuCliente1.add(cadastrarCliente1);

        visualizarCliente1.setText("Visualizar");
        visualizarCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarCliente1ActionPerformed(evt);
            }
        });
        menuCliente1.add(visualizarCliente1);

        alterarCliente1.setText("Alterar");
        alterarCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarCliente1ActionPerformed(evt);
            }
        });
        menuCliente1.add(alterarCliente1);

        deletarCliente1.setText("Deletar");
        deletarCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarCliente1ActionPerformed(evt);
            }
        });
        menuCliente1.add(deletarCliente1);

        transacoes1.add(menuCliente1);

        menuFornecedor1.setText("Fornecedor");

        cadastrarFornecedor1.setText("Cadastrar");
        cadastrarFornecedor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarFornecedor1ActionPerformed(evt);
            }
        });
        menuFornecedor1.add(cadastrarFornecedor1);

        visualizarFornecedor1.setText("Visualizar");
        visualizarFornecedor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarFornecedor1ActionPerformed(evt);
            }
        });
        menuFornecedor1.add(visualizarFornecedor1);

        alterarFornecedor1.setText("Alterar");
        alterarFornecedor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarFornecedor1ActionPerformed(evt);
            }
        });
        menuFornecedor1.add(alterarFornecedor1);

        deletarFornecedor1.setText("Deletar");
        deletarFornecedor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarFornecedor1ActionPerformed(evt);
            }
        });
        menuFornecedor1.add(deletarFornecedor1);

        transacoes1.add(menuFornecedor1);

        menuFuncionario1.setText("Funcionario");
        menuFuncionario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFuncionario1ActionPerformed(evt);
            }
        });

        cadastrarFuncionario1.setText("Cadastrar");
        cadastrarFuncionario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarFuncionario1ActionPerformed(evt);
            }
        });
        menuFuncionario1.add(cadastrarFuncionario1);

        visualizarFuncionarios1.setText("Visualizar");
        visualizarFuncionarios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarFuncionarios1ActionPerformed(evt);
            }
        });
        menuFuncionario1.add(visualizarFuncionarios1);

        alterarFuncionario1.setText("Alterar");
        alterarFuncionario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarFuncionario1ActionPerformed(evt);
            }
        });
        menuFuncionario1.add(alterarFuncionario1);

        deletarFuncionario1.setText("Deletar");
        deletarFuncionario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarFuncionario1ActionPerformed(evt);
            }
        });
        menuFuncionario1.add(deletarFuncionario1);

        transacoes1.add(menuFuncionario1);

        menuProduto1.setText("Produtos");

        cadastrarProduto1.setText("Cadastrar");
        cadastrarProduto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarProduto1ActionPerformed(evt);
            }
        });
        menuProduto1.add(cadastrarProduto1);

        vizualizarrProduto1.setText("Visualizar");
        vizualizarrProduto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vizualizarrProduto1ActionPerformed(evt);
            }
        });
        menuProduto1.add(vizualizarrProduto1);

        alterarrProduto1.setText("Alterar");
        alterarrProduto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarrProduto1ActionPerformed(evt);
            }
        });
        menuProduto1.add(alterarrProduto1);

        deletarrProduto1.setText("Deletar");
        deletarrProduto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarrProduto1ActionPerformed(evt);
            }
        });
        menuProduto1.add(deletarrProduto1);

        transacoes1.add(menuProduto1);

        jMenuBar1.add(transacoes1);

        relatorio.setText("Relatorios");

        relatorioCliente.setText("Relatorio de clientes");
        relatorioCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioClienteActionPerformed(evt);
            }
        });
        relatorio.add(relatorioCliente);

        relatorioFornecedor.setText("Relatorio de fornecedores");
        relatorioFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioFornecedorActionPerformed(evt);
            }
        });
        relatorio.add(relatorioFornecedor);

        relatorioFuncionario.setText("Relatorio de funcionarios");
        relatorioFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioFuncionarioActionPerformed(evt);
            }
        });
        relatorio.add(relatorioFuncionario);

        relatorioProduto.setText("Realatorio de produtos");
        relatorioProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioProdutoActionPerformed(evt);
            }
        });
        relatorio.add(relatorioProduto);

        jMenuBar1.add(relatorio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(campoCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(comboBoxGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(campoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(campoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel10))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(botaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(botaoCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4)
                    .addComponent(campoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(campoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel7)
                        .addComponent(comboBoxGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(campoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCancelar1)
                    .addComponent(botaoLimpar)
                    .addComponent(botaoSalvar))
                .addGap(51, 51, 51))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        Fornecedor fornecedor = new Fornecedor(campoNome.getText(), campoCnpj.getText(),campoTelefone.getText(),campoCidade.getText(),campoEndereco.getText(),
                (comboBoxGrupo.getSelectedItem().toString()));
        if (new CFornecedor().cadastrarFornecedor(fornecedor)) {
            JOptionPane.showMessageDialog(null, "Registro cadastrado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(null, "Falha ao cadastrar registr! Tente novamente.");
        }
        botaoLimparActionPerformed(evt);


    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
        campoNome.setText("");
        campoCnpj.setText("");
        campoTelefone.setText("");
        campoEndereco.setText("");
        campoCidade.setText("");
        comboBoxGrupo.setSelectedItem("");
        

    }//GEN-LAST:event_botaoLimparActionPerformed

    private void botaoCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelar1ActionPerformed
        new Menu().setVisible(true);
        dispose();


    }//GEN-LAST:event_botaoCancelar1ActionPerformed

    private void cadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarClienteActionPerformed
        new CadastroCliente().setVisible(true);
        dispose();
    }//GEN-LAST:event_cadastrarClienteActionPerformed

    private void visualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarClienteActionPerformed
        new VisualizarCliente().setVisible(true);
        dispose();
    }//GEN-LAST:event_visualizarClienteActionPerformed

    private void alterarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarClienteActionPerformed
        new AlterarCliente().setVisible(true);
        dispose();
    }//GEN-LAST:event_alterarClienteActionPerformed

    private void deletarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarClienteActionPerformed
        new DeletarCliente().setVisible(true);
        dispose();
    }//GEN-LAST:event_deletarClienteActionPerformed

    private void menuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClienteActionPerformed

    }//GEN-LAST:event_menuClienteActionPerformed

    private void cadastrarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarFornecedorActionPerformed
        new CadastroFornecedor().setVisible(true);
        dispose();
    }//GEN-LAST:event_cadastrarFornecedorActionPerformed

    private void visualizarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarFornecedorActionPerformed
        new VisualizarFornecedor().setVisible(true);
        dispose();
    }//GEN-LAST:event_visualizarFornecedorActionPerformed

    private void alterarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarFornecedorActionPerformed
        new AlterarFornecedor().setVisible(true);
        dispose();
    }//GEN-LAST:event_alterarFornecedorActionPerformed

    private void deletarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarFornecedorActionPerformed
        new DeletarFornecedor().setVisible(true);
        dispose();
    }//GEN-LAST:event_deletarFornecedorActionPerformed

    private void cadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarFuncionarioActionPerformed
        new CadastroFuncionarios().setVisible(true);
        dispose();
    }//GEN-LAST:event_cadastrarFuncionarioActionPerformed

    private void visualizarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarFuncionariosActionPerformed
        new VisualizarFuncionarios().setVisible(true);
        dispose();
    }//GEN-LAST:event_visualizarFuncionariosActionPerformed

    private void alterarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarFuncionarioActionPerformed
        new AlterarFuncionarios().setVisible(true);
        dispose();
    }//GEN-LAST:event_alterarFuncionarioActionPerformed

    private void deletarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarFuncionarioActionPerformed
        new DeletarFuncionarios().setVisible(true);
        dispose();
    }//GEN-LAST:event_deletarFuncionarioActionPerformed

    private void menuFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFuncionarioActionPerformed

    }//GEN-LAST:event_menuFuncionarioActionPerformed

    private void cadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarProdutoActionPerformed
        new CadastroProduto().setVisible(true);
        dispose();
    }//GEN-LAST:event_cadastrarProdutoActionPerformed

    private void vizualizarrProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vizualizarrProdutoActionPerformed
        new VisualizarProduto().setVisible(true);
        dispose();
    }//GEN-LAST:event_vizualizarrProdutoActionPerformed

    private void alterarrProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarrProdutoActionPerformed
        new AlterarProduto().setVisible(true);
        dispose();
    }//GEN-LAST:event_alterarrProdutoActionPerformed

    private void deletarrProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarrProdutoActionPerformed
        new DeletarProduto().setVisible(true);
        dispose();
    }//GEN-LAST:event_deletarrProdutoActionPerformed

    private void cadastrarCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarCliente1ActionPerformed
        new CadastroCliente().setVisible(true);
        dispose();
    }//GEN-LAST:event_cadastrarCliente1ActionPerformed

    private void visualizarCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarCliente1ActionPerformed
        new VisualizarCliente().setVisible(true);
        dispose();
    }//GEN-LAST:event_visualizarCliente1ActionPerformed

    private void alterarCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarCliente1ActionPerformed
        new AlterarCliente().setVisible(true);
        dispose();
    }//GEN-LAST:event_alterarCliente1ActionPerformed

    private void deletarCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarCliente1ActionPerformed
        new DeletarCliente().setVisible(true);
        dispose();
    }//GEN-LAST:event_deletarCliente1ActionPerformed

    private void menuCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCliente1ActionPerformed

    }//GEN-LAST:event_menuCliente1ActionPerformed

    private void cadastrarFornecedor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarFornecedor1ActionPerformed
        new CadastroFornecedor().setVisible(true);
        dispose();
    }//GEN-LAST:event_cadastrarFornecedor1ActionPerformed

    private void visualizarFornecedor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarFornecedor1ActionPerformed
        new VisualizarFornecedor().setVisible(true);
        dispose();
    }//GEN-LAST:event_visualizarFornecedor1ActionPerformed

    private void alterarFornecedor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarFornecedor1ActionPerformed
        new AlterarFornecedor().setVisible(true);
        dispose();
    }//GEN-LAST:event_alterarFornecedor1ActionPerformed

    private void deletarFornecedor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarFornecedor1ActionPerformed
        new DeletarFornecedor().setVisible(true);
        dispose();
    }//GEN-LAST:event_deletarFornecedor1ActionPerformed

    private void cadastrarFuncionario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarFuncionario1ActionPerformed
        new CadastroFuncionarios().setVisible(true);
        dispose();
    }//GEN-LAST:event_cadastrarFuncionario1ActionPerformed

    private void visualizarFuncionarios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarFuncionarios1ActionPerformed
        new VisualizarFuncionarios().setVisible(true);
        dispose();
    }//GEN-LAST:event_visualizarFuncionarios1ActionPerformed

    private void alterarFuncionario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarFuncionario1ActionPerformed
        new AlterarFuncionarios().setVisible(true);
        dispose();
    }//GEN-LAST:event_alterarFuncionario1ActionPerformed

    private void deletarFuncionario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarFuncionario1ActionPerformed
        new DeletarFuncionarios().setVisible(true);
        dispose();
    }//GEN-LAST:event_deletarFuncionario1ActionPerformed

    private void menuFuncionario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFuncionario1ActionPerformed

    }//GEN-LAST:event_menuFuncionario1ActionPerformed

    private void cadastrarProduto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarProduto1ActionPerformed
        new CadastroProduto().setVisible(true);
        dispose();
    }//GEN-LAST:event_cadastrarProduto1ActionPerformed

    private void vizualizarrProduto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vizualizarrProduto1ActionPerformed
        new VisualizarProduto().setVisible(true);
        dispose();
    }//GEN-LAST:event_vizualizarrProduto1ActionPerformed

    private void alterarrProduto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarrProduto1ActionPerformed
        new AlterarProduto().setVisible(true);
        dispose();
    }//GEN-LAST:event_alterarrProduto1ActionPerformed

    private void deletarrProduto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarrProduto1ActionPerformed
        new DeletarProduto().setVisible(true);
        dispose();
    }//GEN-LAST:event_deletarrProduto1ActionPerformed

    private void relatorioClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioClienteActionPerformed
        RPCliente relatorioGeralCliente = new RPCliente();
        relatorioGeralCliente.gerarRelatorioTotal("E:\\GoBuy-TrabalhoPOE2\\GoBuy-TrabalhoPOE2\\src\\relatorios\\RelatorioCliente.jasper");
    }//GEN-LAST:event_relatorioClienteActionPerformed

    private void relatorioFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioFornecedorActionPerformed
        RPFornecedor relatorioGeralFornecedor = new RPFornecedor();
        relatorioGeralFornecedor.gerarRelatorioTotal("E:\\GoBuy-TrabalhoPOE2\\GoBuy-TrabalhoPOE2\\src\\relatorios\\RelatorioFornecedor.jasper");

    }//GEN-LAST:event_relatorioFornecedorActionPerformed

    private void relatorioFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioFuncionarioActionPerformed
        RPFuncionario relatorioGeralFuncionario = new RPFuncionario();
        relatorioGeralFuncionario.gerarRelatorioTotal("E:\\GoBuy-TrabalhoPOE2\\GoBuy-TrabalhoPOE2\\src\\relatorios\\RelatorioFuncionario.jasper");
    }//GEN-LAST:event_relatorioFuncionarioActionPerformed

    private void relatorioProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioProdutoActionPerformed
        RPProduto relatorioGeralProduto = new RPProduto();
        relatorioGeralProduto.gerarRelatorioTotal("E:\\GoBuy-TrabalhoPOE2\\GoBuy-TrabalhoPOE2\\src\\relatorios\\RelatorioProduto.jasper");
    }//GEN-LAST:event_relatorioProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem alterarCliente1;
    private javax.swing.JMenuItem alterarFornecedor1;
    private javax.swing.JMenuItem alterarFuncionario1;
    private javax.swing.JMenuItem alterarrProduto1;
    private javax.swing.JButton botaoCancelar1;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JMenuItem cadastrarCliente1;
    private javax.swing.JMenuItem cadastrarFornecedor1;
    private javax.swing.JMenuItem cadastrarFuncionario1;
    private javax.swing.JMenuItem cadastrarProduto1;
    private javax.swing.JTextField campoCidade;
    private javax.swing.JTextField campoCnpj;
    private javax.swing.JTextField campoEndereco;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoTelefone;
    private javax.swing.JComboBox<String> comboBoxGrupo;
    private javax.swing.JMenuItem deletarCliente1;
    private javax.swing.JMenuItem deletarFornecedor1;
    private javax.swing.JMenuItem deletarFuncionario1;
    private javax.swing.JMenuItem deletarrProduto1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuCliente1;
    private javax.swing.JMenu menuFornecedor1;
    private javax.swing.JMenu menuFuncionario1;
    private javax.swing.JMenu menuProduto1;
    private javax.swing.JMenu relatorio;
    private javax.swing.JMenuItem relatorioCliente;
    private javax.swing.JMenuItem relatorioFornecedor;
    private javax.swing.JMenuItem relatorioFuncionario;
    private javax.swing.JMenuItem relatorioProduto;
    private javax.swing.JMenu transacoes1;
    private javax.swing.JMenuItem visualizarCliente1;
    private javax.swing.JMenuItem visualizarFornecedor1;
    private javax.swing.JMenuItem visualizarFuncionarios1;
    private javax.swing.JMenuItem vizualizarrProduto1;
    // End of variables declaration//GEN-END:variables
}
