/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao.telas;

import controlador.CFornecedor;
import javax.swing.JOptionPane;
import modelo.dominio.Fornecedor;
import relatorios.RPCliente;
import relatorios.RPFornecedor;
import relatorios.RPFuncionario;
import relatorios.RPProduto;
/**
 *
 * @author Junior
 */
public class FormularioAlterarFornecedor extends javax.swing.JFrame {
    int auxCodigo;
    /**
     * Creates new form FormularioAlterarFornecedor
     */
    public FormularioAlterarFornecedor() {
        initComponents();
    }
    
    public FormularioAlterarFornecedor(Fornecedor fornecedor) 
    {
        initComponents();
       
        auxCodigo = fornecedor.getId();
        campoNome.setText(fornecedor.getNomeFornecedor());
        campoCnpj.setText(fornecedor.getCnpj());
        campoTelefone.setText(fornecedor.getTelefone());
        campoCidade.setText(fornecedor.getCidade());
        campoEndereco.setText(fornecedor.getEndereco());
        comboBoxGrupo.setSelectedItem(fornecedor.getGrupoComprador());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botaoAtualizar = new javax.swing.JButton();
        botaoFechar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        campoCnpj = new javax.swing.JTextField();
        comboBoxGrupo = new javax.swing.JComboBox<>();
        campoTelefone = new javax.swing.JTextField();
        campoEndereco = new javax.swing.JTextField();
        campoCidade = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        transacoes = new javax.swing.JMenu();
        menuCliente = new javax.swing.JMenu();
        cadastrarCliente = new javax.swing.JMenuItem();
        visualizarCliente = new javax.swing.JMenuItem();
        alterarCliente = new javax.swing.JMenuItem();
        deletarCliente = new javax.swing.JMenuItem();
        menuFornecedor = new javax.swing.JMenu();
        cadastrarFornecedor = new javax.swing.JMenuItem();
        visualizarFornecedor = new javax.swing.JMenuItem();
        alterarFornecedor = new javax.swing.JMenuItem();
        deletarFornecedor = new javax.swing.JMenuItem();
        menuFuncionario = new javax.swing.JMenu();
        cadastrarFuncionario = new javax.swing.JMenuItem();
        visualizarFuncionarios = new javax.swing.JMenuItem();
        alterarFuncionario = new javax.swing.JMenuItem();
        deletarFuncionario = new javax.swing.JMenuItem();
        menuProduto = new javax.swing.JMenu();
        cadastrarProduto = new javax.swing.JMenuItem();
        vizualizarrProduto = new javax.swing.JMenuItem();
        alterarrProduto = new javax.swing.JMenuItem();
        deletarrProduto = new javax.swing.JMenuItem();
        relatorio1 = new javax.swing.JMenu();
        relatorioCliente1 = new javax.swing.JMenuItem();
        relatorioFornecedor1 = new javax.swing.JMenuItem();
        relatorioFuncionario1 = new javax.swing.JMenuItem();
        relatorioProduto1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        botaoAtualizar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoAtualizar.setText("Atualizar");
        botaoAtualizar.setPreferredSize(new java.awt.Dimension(79, 31));
        botaoAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtualizarActionPerformed(evt);
            }
        });

        botaoFechar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoFechar.setText("Fechar");
        botaoFechar.setPreferredSize(new java.awt.Dimension(79, 31));
        botaoFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFecharActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Atualizar Fornecedor");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Nome do Fornecedor:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("CNPJ:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Grupo de comprador:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Telefone:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Endereço:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Cidade:");

        comboBoxGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "   ", "Bebidas", "Mercearia seca doce", "Mercearia seca salgada", "Perecivel", "Perfumaria Hipel", " " }));

        campoEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEnderecoActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addGap(4, 4, 4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoCnpj, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campoNome, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(comboBoxGrupo, 0, 159, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(campoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoEndereco)
                            .addComponent(campoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(botaoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addComponent(botaoFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel10))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(campoCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(comboBoxGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(campoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(campoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(campoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoFechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        transacoes.setText("Transações");

        menuCliente.setText("Cliente");
        menuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClienteActionPerformed(evt);
            }
        });

        cadastrarCliente.setText("Cadastrar");
        cadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarClienteActionPerformed(evt);
            }
        });
        menuCliente.add(cadastrarCliente);

        visualizarCliente.setText("Visualizar");
        visualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarClienteActionPerformed(evt);
            }
        });
        menuCliente.add(visualizarCliente);

        alterarCliente.setText("Alterar");
        alterarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarClienteActionPerformed(evt);
            }
        });
        menuCliente.add(alterarCliente);

        deletarCliente.setText("Deletar");
        deletarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarClienteActionPerformed(evt);
            }
        });
        menuCliente.add(deletarCliente);

        transacoes.add(menuCliente);

        menuFornecedor.setText("Fornecedor");

        cadastrarFornecedor.setText("Cadastrar");
        cadastrarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarFornecedorActionPerformed(evt);
            }
        });
        menuFornecedor.add(cadastrarFornecedor);

        visualizarFornecedor.setText("Visualizar");
        visualizarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarFornecedorActionPerformed(evt);
            }
        });
        menuFornecedor.add(visualizarFornecedor);

        alterarFornecedor.setText("Alterar");
        alterarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarFornecedorActionPerformed(evt);
            }
        });
        menuFornecedor.add(alterarFornecedor);

        deletarFornecedor.setText("Deletar");
        deletarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarFornecedorActionPerformed(evt);
            }
        });
        menuFornecedor.add(deletarFornecedor);

        transacoes.add(menuFornecedor);

        menuFuncionario.setText("Funcionario");
        menuFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFuncionarioActionPerformed(evt);
            }
        });

        cadastrarFuncionario.setText("Cadastrar");
        cadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarFuncionarioActionPerformed(evt);
            }
        });
        menuFuncionario.add(cadastrarFuncionario);

        visualizarFuncionarios.setText("Visualizar");
        visualizarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarFuncionariosActionPerformed(evt);
            }
        });
        menuFuncionario.add(visualizarFuncionarios);

        alterarFuncionario.setText("Alterar");
        alterarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarFuncionarioActionPerformed(evt);
            }
        });
        menuFuncionario.add(alterarFuncionario);

        deletarFuncionario.setText("Deletar");
        deletarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarFuncionarioActionPerformed(evt);
            }
        });
        menuFuncionario.add(deletarFuncionario);

        transacoes.add(menuFuncionario);

        menuProduto.setText("Produtos");

        cadastrarProduto.setText("Cadastrar");
        cadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarProdutoActionPerformed(evt);
            }
        });
        menuProduto.add(cadastrarProduto);

        vizualizarrProduto.setText("Visualizar");
        vizualizarrProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vizualizarrProdutoActionPerformed(evt);
            }
        });
        menuProduto.add(vizualizarrProduto);

        alterarrProduto.setText("Alterar");
        alterarrProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarrProdutoActionPerformed(evt);
            }
        });
        menuProduto.add(alterarrProduto);

        deletarrProduto.setText("Deletar");
        deletarrProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarrProdutoActionPerformed(evt);
            }
        });
        menuProduto.add(deletarrProduto);

        transacoes.add(menuProduto);

        jMenuBar1.add(transacoes);

        relatorio1.setText("Relatorios");

        relatorioCliente1.setText("Relatorio de clientes");
        relatorioCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioCliente1ActionPerformed(evt);
            }
        });
        relatorio1.add(relatorioCliente1);

        relatorioFornecedor1.setText("Relatorio de fornecedores");
        relatorioFornecedor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioFornecedor1ActionPerformed(evt);
            }
        });
        relatorio1.add(relatorioFornecedor1);

        relatorioFuncionario1.setText("Relatorio de funcionarios");
        relatorioFuncionario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioFuncionario1ActionPerformed(evt);
            }
        });
        relatorio1.add(relatorioFuncionario1);

        relatorioProduto1.setText("Realatorio de produtos");
        relatorioProduto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioProduto1ActionPerformed(evt);
            }
        });
        relatorio1.add(relatorioProduto1);

        jMenuBar1.add(relatorio1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtualizarActionPerformed
        Fornecedor fornecedor = new Fornecedor(auxCodigo,campoNome.getText(), campoCnpj.getText(),campoTelefone.getText(),campoCidade.getText(),campoEndereco.getText(),
                (comboBoxGrupo.getSelectedItem().toString()));
        if(new CFornecedor().atualizarFornecedor(fornecedor))
        {
            JOptionPane.showMessageDialog(null, "Registro atualizado com sucesso!");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Falha ao atualizar registro! Tente novamente.");
        }
        this.dispose();
        new FormularioAlterarFornecedor().setVisible(true);
    }//GEN-LAST:event_botaoAtualizarActionPerformed

    private void botaoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFecharActionPerformed
        new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoFecharActionPerformed

    private void campoEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEnderecoActionPerformed

    private void cadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarClienteActionPerformed
        new CadastroCliente().setVisible(true);
        dispose();
    }//GEN-LAST:event_cadastrarClienteActionPerformed

    private void visualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarClienteActionPerformed
        new VisualizarCliente().setVisible(true);
        dispose();
    }//GEN-LAST:event_visualizarClienteActionPerformed

    private void alterarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarClienteActionPerformed
        new AlterarCliente().setVisible(true);
        dispose();
    }//GEN-LAST:event_alterarClienteActionPerformed

    private void deletarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarClienteActionPerformed
        new DeletarCliente().setVisible(true);
        dispose();
    }//GEN-LAST:event_deletarClienteActionPerformed

    private void menuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClienteActionPerformed

    }//GEN-LAST:event_menuClienteActionPerformed

    private void cadastrarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarFornecedorActionPerformed
        new CadastroFornecedor().setVisible(true);
        dispose();
    }//GEN-LAST:event_cadastrarFornecedorActionPerformed

    private void visualizarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarFornecedorActionPerformed
        new VisualizarFornecedor().setVisible(true);
        dispose();
    }//GEN-LAST:event_visualizarFornecedorActionPerformed

    private void alterarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarFornecedorActionPerformed
        new AlterarFornecedor().setVisible(true);
        dispose();
    }//GEN-LAST:event_alterarFornecedorActionPerformed

    private void deletarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarFornecedorActionPerformed
        new DeletarFornecedor().setVisible(true);
        dispose();
    }//GEN-LAST:event_deletarFornecedorActionPerformed

    private void cadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarFuncionarioActionPerformed
        new CadastroFuncionarios().setVisible(true);
        dispose();
    }//GEN-LAST:event_cadastrarFuncionarioActionPerformed

    private void visualizarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarFuncionariosActionPerformed
        new VisualizarFuncionarios().setVisible(true);
        dispose();
    }//GEN-LAST:event_visualizarFuncionariosActionPerformed

    private void alterarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarFuncionarioActionPerformed
        new AlterarFuncionarios().setVisible(true);
        dispose();
    }//GEN-LAST:event_alterarFuncionarioActionPerformed

    private void deletarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarFuncionarioActionPerformed
        new DeletarFuncionarios().setVisible(true);
        dispose();
    }//GEN-LAST:event_deletarFuncionarioActionPerformed

    private void menuFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFuncionarioActionPerformed

    }//GEN-LAST:event_menuFuncionarioActionPerformed

    private void cadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarProdutoActionPerformed
        new CadastroProduto().setVisible(true);
        dispose();
    }//GEN-LAST:event_cadastrarProdutoActionPerformed

    private void vizualizarrProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vizualizarrProdutoActionPerformed
        new VisualizarProduto().setVisible(true);
        dispose();
    }//GEN-LAST:event_vizualizarrProdutoActionPerformed

    private void alterarrProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarrProdutoActionPerformed
        new AlterarProduto().setVisible(true);
        dispose();
    }//GEN-LAST:event_alterarrProdutoActionPerformed

    private void deletarrProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarrProdutoActionPerformed
        new DeletarProduto().setVisible(true);
        dispose();
    }//GEN-LAST:event_deletarrProdutoActionPerformed

    private void relatorioClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioClienteActionPerformed
        RPCliente relatorioGeralCliente = new RPCliente();
        relatorioGeralCliente.gerarRelatorioTotal("E:\\GoBuy-TrabalhoPOE2\\GoBuy-TrabalhoPOE2\\src\\relatorios\\RelatorioCliente.jasper");
    }//GEN-LAST:event_relatorioClienteActionPerformed

    private void relatorioFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioFornecedorActionPerformed
        RPFornecedor relatorioGeralFornecedor = new RPFornecedor();
        relatorioGeralFornecedor.gerarRelatorioTotal("E:\\GoBuy-TrabalhoPOE2\\GoBuy-TrabalhoPOE2\\src\\relatorios\\RelatorioFornecedor.jasper");

    }//GEN-LAST:event_relatorioFornecedorActionPerformed

    private void relatorioFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioFuncionarioActionPerformed
        RPFuncionario relatorioGeralFuncionario = new RPFuncionario();
        relatorioGeralFuncionario.gerarRelatorioTotal("E:\\GoBuy-TrabalhoPOE2\\GoBuy-TrabalhoPOE2\\src\\relatorios\\RelatorioFuncionario.jasper");
    }//GEN-LAST:event_relatorioFuncionarioActionPerformed

    private void relatorioProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioProdutoActionPerformed
        RPProduto relatorioGeralProduto = new RPProduto();
        relatorioGeralProduto.gerarRelatorioTotal("E:\\GoBuy-TrabalhoPOE2\\GoBuy-TrabalhoPOE2\\src\\relatorios\\RelatorioProduto.jasper");
    }//GEN-LAST:event_relatorioProdutoActionPerformed

    private void relatorioCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioCliente1ActionPerformed
        RPCliente relatorioGeralCliente = new RPCliente();
        relatorioGeralCliente.gerarRelatorioTotal("E:\\GoBuy-TrabalhoPOE2\\GoBuy-TrabalhoPOE2\\src\\relatorios\\RelatorioCliente.jasper");
    }//GEN-LAST:event_relatorioCliente1ActionPerformed

    private void relatorioFornecedor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioFornecedor1ActionPerformed
        RPFornecedor relatorioGeralFornecedor = new RPFornecedor();
        relatorioGeralFornecedor.gerarRelatorioTotal("E:\\GoBuy-TrabalhoPOE2\\GoBuy-TrabalhoPOE2\\src\\relatorios\\RelatorioFornecedor.jasper");

    }//GEN-LAST:event_relatorioFornecedor1ActionPerformed

    private void relatorioFuncionario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioFuncionario1ActionPerformed
        RPFuncionario relatorioGeralFuncionario = new RPFuncionario();
        relatorioGeralFuncionario.gerarRelatorioTotal("E:\\GoBuy-TrabalhoPOE2\\GoBuy-TrabalhoPOE2\\src\\relatorios\\RelatorioFuncionario.jasper");
    }//GEN-LAST:event_relatorioFuncionario1ActionPerformed

    private void relatorioProduto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioProduto1ActionPerformed
        RPProduto relatorioGeralProduto = new RPProduto();
        relatorioGeralProduto.gerarRelatorioTotal("E:\\GoBuy-TrabalhoPOE2\\GoBuy-TrabalhoPOE2\\src\\relatorios\\RelatorioProduto.jasper");
    }//GEN-LAST:event_relatorioProduto1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioAlterarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioAlterarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioAlterarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioAlterarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioAlterarFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem alterarCliente;
    private javax.swing.JMenuItem alterarFornecedor;
    private javax.swing.JMenuItem alterarFuncionario;
    private javax.swing.JMenuItem alterarrProduto;
    private javax.swing.JButton botaoAtualizar;
    private javax.swing.JButton botaoFechar;
    private javax.swing.JMenuItem cadastrarCliente;
    private javax.swing.JMenuItem cadastrarFornecedor;
    private javax.swing.JMenuItem cadastrarFuncionario;
    private javax.swing.JMenuItem cadastrarProduto;
    private javax.swing.JTextField campoCidade;
    private javax.swing.JTextField campoCnpj;
    private javax.swing.JTextField campoEndereco;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoTelefone;
    private javax.swing.JComboBox<String> comboBoxGrupo;
    private javax.swing.JMenuItem deletarCliente;
    private javax.swing.JMenuItem deletarFornecedor;
    private javax.swing.JMenuItem deletarFuncionario;
    private javax.swing.JMenuItem deletarrProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuCliente;
    private javax.swing.JMenu menuFornecedor;
    private javax.swing.JMenu menuFuncionario;
    private javax.swing.JMenu menuProduto;
    private javax.swing.JMenu relatorio1;
    private javax.swing.JMenuItem relatorioCliente1;
    private javax.swing.JMenuItem relatorioFornecedor1;
    private javax.swing.JMenuItem relatorioFuncionario1;
    private javax.swing.JMenuItem relatorioProduto1;
    private javax.swing.JMenu transacoes;
    private javax.swing.JMenuItem visualizarCliente;
    private javax.swing.JMenuItem visualizarFornecedor;
    private javax.swing.JMenuItem visualizarFuncionarios;
    private javax.swing.JMenuItem vizualizarrProduto;
    // End of variables declaration//GEN-END:variables
}
